language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_install:
  - mkdir bootstrap/cache
  - cp .env.example .env
  - php artisan key:generate
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

script: vendor/bin/phpunit